#!/usr/bin/env bash
# install HAproxy

sudo apt-get install -y software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy
sudo apt-get -y update
sudo apt-get install -y haproxy

sudo echo "ENABLED=1" > /etc/default/haproxy

echo "
	listen load_balancer
	bind *:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server 190869-web-01 100.26.233.228:80 check
	server 190869-web-02 34.229.67.124:80 check
">> /etc/haproxy/haproxy.cfg

sudo service haproxy start
sudo service haproxy restart
