#!/usr/bin/env bash
# Install nginx on your web-01 server

apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
ufw allow 'SSH'
echo "Hello World!" > /var/www/html/index.html
sudo service nginx restart
